services:
  - type: web
    name: ibrood
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: API_URL
        value: https://rozu1726-ibrood-app.hf.space
      - key: NEXT_PUBLIC_API_URL
        value: https://rozu1726-ibrood-app.hf.space
      - key: HUGGINGFACE_HUB_CACHE
        value: /tmp/hf_cache
      - key: RENDER_CACHE_DIR
        value: /tmp/model_cache
