services:
  - type: web
    name: ibrood-pwa
    env: node
    region: oregon
    plan: hobby
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production